import {SaveState} from "../components/Table";

export const getExportString = (data: SaveState): string => {
    return btoa(JSON.stringify(data));
};

export const getImportData = (data: string): SaveState => {
    return JSON.parse(atob(data));
};

export const getGoodSave = (): string => "eyJib2FyZCI6W1t7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn0seyJsZXR0ZXIiOiIifSx7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn1dLFt7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn0seyJsZXR0ZXIiOiIifSx7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn1dLFt7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn0seyJsZXR0ZXIiOiIifSx7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn1dLFt7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn0seyJsZXR0ZXIiOiIifSx7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn1dLFt7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn0seyJsZXR0ZXIiOiIifSx7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn1dLFt7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn0seyJsZXR0ZXIiOiIifSx7ImxldHRlciI6IiJ9LHsibGV0dGVyIjoiIn1dXSwic3RhdHMiOnsibGV2ZWwiOjMsImV4cCI6OCwiY29ycmVjdCI6MjgsIndyb25nIjowfSwiaXNMb3NlIjpmYWxzZSwiaXNXaW4iOmZhbHNlLCJwb2ludGVyIjp7InJvdyI6MCwiY29sIjowfSwiY29ycmVjdFdvcmQiOiJmbGVncyJ90";